package calculadora;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.event.ActionEvent;

public class CalculadoraController {
	@FXML
	private Button sieteButton;
	@FXML
	private Button ochoButton;
	@FXML
	private Button NueveButton;
	@FXML
	private Button CuatroButton;
	@FXML
	private Button unoButton;
	@FXML
	private Button ceroButton;
	@FXML
	private Button cincoButton;
	@FXML
	private Button dosButton;
	@FXML
	private Button seisButton;
	@FXML
	private Button coma;
	@FXML
	private Button sumar;
	@FXML
	private Button Restar;
	@FXML
	private Button Multiplicar;
	@FXML
	private Button borrarTodo;
	@FXML
	private Button BorrarUltimo;
	@FXML
	private Button Dvidir;
	@FXML
	private Button igual;
	@FXML
	private TextField mostrarTextField;
	
	String operator1="",operator2;
	String operador="";

	// Event Listener on Button[#sieteButton].onAction
	@FXML
	public void pulsarUno(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	public void pulsarDos(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void pulsarTres(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void pulsarCuatro(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void pulsarCinco(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	public void pulsarSeis(ActionEvent event) {
		// TODO Autogenerated
	}
	
	public void pulsarSiete(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	public void pulsarOcho(ActionEvent event) {
		
		
		mostrarTextField.setText(operator1+"8");
		
	}
	
	public void pulsarNueve(ActionEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#ochoButton].onAction
	@FXML
	public void pulsarMas(ActionEvent event) {
			
		System.out.println(operator1 + "+");
		
	}
	// Event Listener on Button[#NueveButton].onAction
	@FXML
	public void PulsarIgual(ActionEvent event) {
		
		
		if(operador=="+") { 
	//		cast (operator1)  
			}
		else if(operador=="-") {
			
		}else if(operador=="*") {
			
		}
		
	}
	
	
	//public mostrar
	
	//public void getView() {
//		return calculadora ;
//	}
	
}
